import { config as envConfig } from "dotenv"
envConfig({ path: "./.env.development" })

export const config = {
  NODE_ENV: process.env.NODE_ENV,
  PLATFORM_NAME: process.env.PLATFORM_NAME,
  AZURE_COSMOS_DB_CONNECTION_STRING:
    process.env.AZURE_COSMOS_DB_CONNECTION_STRING,
  AZURE_APP_CONFIG_CONNECTION_STRING:
    process.env.AZURE_APP_CONFIG_CONNECTION_STRING,
  AZURE_OPENAI_API_KEY: process.env.AZURE_OPENAI_API_KEY,
  AZURE_OPENAI_DEPLOYMENT_URI: process.env.AZURE_OPENAI_DEPLOYMENT_URI,
  AZURE_OPENAZURE_OPENAI_NAME: process.env.AZURE_OPENAZURE_OPENAI_NAME,
  NEWS_API_URI: process.env.NEWS_API_URI,
  JWT_SECRET_ACCESS_TOKEN: process.env.JWT_SECRET_ACCESS_TOKEN,
  JWT_SECRET_REFRESH_TOKEN: process.env.JWT_SECRET_REFRESH_TOKEN,
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
  GOOGLE_OAUTH_REDIRECT_URI: process.env.GOOGLE_OAUTH_REDIRECT_URI,
  UI_URL: process.env.UI_URL,
}
