import { config as envConfig } from "dotenv"
envConfig({ path: "./.env.development" })

export const config = {
  NODE_ENV: process.env.NODE_ENV,
  PLATFORM_NAME: process.env.PLATFORM_NAME,
  AUTH_DATABASE_URI: process.env.AUTH_DATABASE_URI,
  PLATFORM_DATABASE_URI: process.env.PLATFORM_DATABASE_URI,
  APPS_DATABASE_URI: process.env.APPS_DATABASE_URI,
  REDIS_URI: process.env.REDIS_URI,
  AI_MODEL_API_KEY: process.env.AI_MODEL_API_KEY,
  AI_MODEL_DEPLOYMENT_URI: process.env.AI_MODEL_DEPLOYMENT_URI,
  AI_MODEL_MODEL_NAME: process.env.AI_MODEL_MODEL_NAME,
  NEWS_API_URI: process.env.NEWS_API_URI,
  JWT_SECRET_ACCESS_TOKEN: process.env.JWT_SECRET_ACCESS_TOKEN,
  JWT_SECRET_REFRESH_TOKEN: process.env.JWT_SECRET_REFRESH_TOKEN,
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
  GOOGLE_OAUTH_REDIRECT_URI: process.env.GOOGLE_OAUTH_REDIRECT_URI,
  UI_URL: process.env.UI_URL,
}
