name: CI-CD-PIPELINE

on:
  push:
    branches:
      - main

jobs:
  CORE-SERVICE-DEPLOYMENT:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PROD_API }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Build API Gateway application
        working-directory: services/core-service
        run: |
          npm install
          CI=false npm run build

      - name: Configure packages
        working-directory: services/core-service
        run: jq 'del(.devDependencies)' package.json > temp.json && mv temp.json package.json

      - name: Pull Vercel Environment Information
        working-directory: services/core-service
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: services/core-service
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Publish Project Artifacts to Vercel
        working-directory: services/core-service
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  UI-SERVICE-DEPLOYMENT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: services/ui-service
        run: npm install

      - name: Build Next.js
        working-directory: services/ui-service
        env:
          NEXT_PUBLIC_PLATFORM_NAME: ${{ secrets.NEXT_PUBLIC_PLATFORM_NAME }}
          NEXT_PUBLIC_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_CLIENT_ID }}
          NEXT_PUBLIC_CORE_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_CORE_SERVICE_URL }}
        run: npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: wallstreet
          publish-profile: ${{ secrets.AZURE_UI_APP_PUBLISH_PROFILE }}
          package: services/ui-service

  CRON-SERVICE-DEPLOYMENT:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PROD_CRON }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        working-directory: services/cron-service
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: services/cron-service
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Publish Project Artifacts to Vercel
        working-directory: services/cron-service
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
